const items = [

/* ================= ELECTRONICS (10) ================= */
{
  id: 1,
  name: "Wireless Headphones",
  category: "electronics",
  price: 1200,
  sellingPrice: 1200,
  originalPrice: 2500,
  condition: "Like New",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Wireless headphones with clear sound and long battery life.",
  specs: { type: "Over-Ear", connectivity: "Bluetooth", battery: "20 hrs" },
  sellerName: "Student Seller",
  contact: "9876543210",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/headphones.jpg"
},
{
  id: 2,
  name: "Bluetooth Speaker",
  category: "electronics",
  price: 900,
  sellingPrice: 900,
  originalPrice: 1800,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Portable Bluetooth speaker with loud sound output.",
  specs: { output: "10W", connectivity: "Bluetooth" },
  sellerName: "Student Seller",
  contact: "9123456789",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/speaker.jpg"
},
{
  id: 3,
  name: "Electric Kettle",
  category: "electronics",
  price: 800,
  sellingPrice: 800,
  originalPrice: 1500,
  condition: "Good",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Electric kettle suitable for hostel use.",
  specs: { capacity: "1.5 L", power: "1500W" },
  sellerName: "Student Seller",
  contact: "9012345678",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/kettle.jpg"
},
{
  id: 4,
  name: "Power Bank",
  category: "electronics",
  price: 700,
  sellingPrice: 700,
  originalPrice: 1400,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Fast charging power bank for mobile devices.",
  specs: { capacity: "10000 mAh", output: "Fast Charge" },
  sellerName: "Student Seller",
  contact: "8899776655",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/power_bank.jpg"
},
{
  id: 5,
  name: "USB Charger",
  category: "electronics",
  price: 300,
  sellingPrice: 300,
  originalPrice: 600,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "USB charger with fast charging support.",
  specs: { ports: "2 USB", output: "18W" },
  sellerName: "Student Seller",
  contact: "9988776655",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/extension_box.jpg"
},
{
  id: 6,
  name: "Earphones",
  category: "electronics",
  price: 400,
  sellingPrice: 400,
  originalPrice: 800,
  condition: "Used",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Wired earphones with clear microphone.",
  specs: { type: "In-Ear", mic: "Yes" },
  sellerName: "Student Seller",
  contact: "9090909090",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/headphones.jpg"
},
{
  id: 7,
  name: "Extension Box",
  category: "electronics",
  price: 350,
  sellingPrice: 350,
  originalPrice: 700,
  condition: "Good",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Extension box with multiple sockets.",
  specs: { sockets: "4", switch: "Yes" },
  sellerName: "Student Seller",
  contact: "9191919191",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/extension_box.jpg"
},
{
  id: 8,
  name: "Table Lamp",
  category: "electronics",
  price: 600,
  sellingPrice: 600,
  originalPrice: 1200,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "LED table lamp for night study.",
  specs: { light: "LED", power: "USB" },
  sellerName: "Student Seller",
  contact: "9345678901",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/study_lamp.jpg"
},
{
  id: 9,
  name: "Wireless Mouse",
  category: "electronics",
  price: 250,
  sellingPrice: 250,
  originalPrice: 500,
  condition: "Used",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Wireless mouse with smooth tracking.",
  specs: { dpi: "1200", connectivity: "Wireless" },
  sellerName: "Student Seller",
  contact: "9871234560",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/mouse.jpg"
},
{
  id: 10,
  name: "Keyboard",
  category: "electronics",
  price: 450,
  sellingPrice: 450,
  originalPrice: 900,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "USB keyboard suitable for laptops and desktops.",
  specs: { type: "Wired", keys: "104" },
  sellerName: "Student Seller",
  contact: "9812345670",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/key_board.jpg"
},

/* ================= BOOKS (10) ================= */
{
  id: 11,
  name: "Operating Systems Book",
  category: "books",
  price: 350,
  sellingPrice: 350,
  originalPrice: 650,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Operating Systems textbook for engineering students.",
  specs: { author: "Galvin", edition: "9th" },
  sellerName: "Student Seller",
  contact: "9123987654",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 12,
  name: "DBMS Book",
  category: "books",
  price: 400,
  sellingPrice: 400,
  originalPrice: 700,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Database Management Systems textbook.",
  specs: { author: "Korth", edition: "6th" },
  sellerName: "Student Seller",
  contact: "9345612345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 13,
  name: "Data Structures Book",
  category: "books",
  price: 450,
  sellingPrice: 450,
  originalPrice: 800,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Data Structures using C textbook.",
  specs: { author: "Seymour Lipschutz" },
  sellerName: "Student Seller",
  contact: "9988123456",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 14,
  name: "Java Programming",
  category: "books",
  price: 500,
  sellingPrice: 500,
  originalPrice: 900,
  condition: "Like New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Java programming reference book.",
  specs: { author: "Herbert Schildt" },
  sellerName: "Student Seller",
  contact: "9876501234",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 15,
  name: "Python Basics",
  category: "books",
  price: 380,
  sellingPrice: 380,
  originalPrice: 700,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Introductory Python programming book.",
  specs: { level: "Beginner" },
  sellerName: "Student Seller",
  contact: "9765432109",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 16,
  name: "Computer Networks",
  category: "books",
  price: 420,
  sellingPrice: 420,
  originalPrice: 750,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Computer Networks textbook.",
  specs: { author: "Tanenbaum" },
  sellerName: "Student Seller",
  contact: "9654321098",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 17,
  name: "C Programming",
  category: "books",
  price: 300,
  sellingPrice: 300,
  originalPrice: 600,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "C programming fundamentals book.",
  specs: { author: "Dennis Ritchie" },
  sellerName: "Student Seller",
  contact: "9543210987",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 18,
  name: "Discrete Mathematics",
  category: "books",
  price: 390,
  sellingPrice: 390,
  originalPrice: 720,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Discrete Mathematics for computer science.",
  specs: { topics: "Graphs, Logic" },
  sellerName: "Student Seller",
  contact: "9432109876",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 19,
  name: "AI Basics",
  category: "books",
  price: 520,
  sellingPrice: 520,
  originalPrice: 900,
  condition: "Like New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Introduction to Artificial Intelligence.",
  specs: { level: "Beginner" },
  sellerName: "Student Seller",
  contact: "9321098765",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},
{
  id: 20,
  name: "Web Development",
  category: "books",
  price: 480,
  sellingPrice: 480,
  originalPrice: 850,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "HTML, CSS, JavaScript web development guide.",
  specs: { stack: "HTML/CSS/JS" },
  sellerName: "Student Seller",
  contact: "9210987654",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/book.jpg"
},

/* ================= FURNITURE (10) ================= */
{
  id: 21,
  name: "Study Chair",
  category: "furniture",
  price: 900,
  sellingPrice: 900,
  originalPrice: 1800,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Comfortable chair for study use.",
  specs: { material: "Plastic" },
  sellerName: "Student Seller",
  contact: "9870012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/chair.jpg"
},
{
  id: 22,
  name: "Office Chair",
  category: "furniture",
  price: 1200,
  sellingPrice: 1200,
  originalPrice: 2500,
  condition: "Good",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Office chair with back support.",
  specs: { material: "Metal + Foam" },
  sellerName: "Student Seller",
  contact: "9867012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/chair.jpg"
},
{
  id: 23,
  name: "Laptop Table",
  category: "furniture",
  price: 800,
  sellingPrice: 800,
  originalPrice: 1600,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Portable laptop table.",
  specs: { foldable: "Yes" },
  sellerName: "Student Seller",
  contact: "9854012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/laptop_stand.jpg"
},
{
  id: 24,
  name: "Study Desk",
  category: "furniture",
  price: 1500,
  sellingPrice: 1500,
  originalPrice: 3000,
  condition: "Used",
  yearsUsed: 3,
  yearBought: 2022,
  description: "Wooden study desk with drawers.",
  specs: { drawers: "Yes" },
  sellerName: "Student Seller",
  contact: "9841012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},
{
  id: 25,
  name: "Bookshelf",
  category: "furniture",
  price: 1100,
  sellingPrice: 1100,
  originalPrice: 2200,
  condition: "Good",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Bookshelf for storing books.",
  specs: { shelves: "4" },
  sellerName: "Student Seller",
  contact: "9830012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},
{
  id: 26,
  name: "Bedside Table",
  category: "furniture",
  price: 700,
  sellingPrice: 700,
  originalPrice: 1400,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Small bedside table.",
  specs: { material: "Wood" },
  sellerName: "Student Seller",
  contact: "9829012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/bes_sidetable.jpg"
},
{
  id: 27,
  name: "Plastic Stool",
  category: "furniture",
  price: 250,
  sellingPrice: 250,
  originalPrice: 500,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Lightweight plastic stool.",
  specs: { color: "Brown" },
  sellerName: "Student Seller",
  contact: "9818012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/chair.jpg"
},
{
  id: 28,
  name: "Wooden Table",
  category: "furniture",
  price: 1800,
  sellingPrice: 1800,
  originalPrice: 3600,
  condition: "Used",
  yearsUsed: 3,
  yearBought: 2022,
  description: "Strong wooden table.",
  specs: { material: "Wood" },
  sellerName: "Student Seller",
  contact: "9817012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/laptop_stand.jpg"
},
{
  id: 29,
  name: "Drawer Unit",
  category: "furniture",
  price: 1300,
  sellingPrice: 1300,
  originalPrice: 2600,
  condition: "Good",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Drawer unit for storage.",
  specs: { drawers: "3" },
  sellerName: "Student Seller",
  contact: "9816012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},
{
  id: 30,
  name: "Cupboard",
  category: "furniture",
  price: 2000,
  sellingPrice: 2000,
  originalPrice: 4000,
  condition: "Used",
  yearsUsed: 3,
  yearBought: 2022,
  description: "Cupboard for clothes and storage.",
  specs: { shelves: "Yes" },
  sellerName: "Student Seller",
  contact: "9815012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},

/* ================= DAILY ESSENTIALS (10) ================= */
{
  id: 31,
  name: "Lunch Box Set",
  category: "daily",
  price: 300,
  sellingPrice: 300,
  originalPrice: 600,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Lunch box set for students.",
  specs: { pieces: "3" },
  sellerName: "Student Seller",
  contact: "9814012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/lunch_box.jpg"
},
{
  id: 32,
  name: "Water Bottle",
  category: "daily",
  price: 200,
  sellingPrice: 200,
  originalPrice: 400,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Reusable water bottle.",
  specs: { capacity: "1 L" },
  sellerName: "Student Seller",
  contact: "9813012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/water_bottle.jpg"
},
{
  id: 33,
  name: "Electric Kettle",
  category: "daily",
  price: 800,
  sellingPrice: 800,
  originalPrice: 1500,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Electric kettle for daily use.",
  specs: { capacity: "1.5 L" },
  sellerName: "Student Seller",
  contact: "9812012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/kettle.jpg"
},
{
  id: 34,
  name: "Mug Set",
  category: "daily",
  price: 150,
  sellingPrice: 150,
  originalPrice: 300,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Ceramic mug set.",
  specs: { pieces: "2" },
  sellerName: "Student Seller",
  contact: "9811012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/mug.jpg"
},
{
  id: 35,
  name: "Plate & Bowl Set",
  category: "daily",
  price: 250,
  sellingPrice: 250,
  originalPrice: 500,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Plate and bowl set.",
  specs: { pieces: "4" },
  sellerName: "Student Seller",
  contact: "9810012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/bowl.jpg"
},
{
  id: 36,
  name: "Thermos Flask",
  category: "daily",
  price: 400,
  sellingPrice: 400,
  originalPrice: 800,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Thermos flask keeps drinks hot or cold.",
  specs: { capacity: "750 ml" },
  sellerName: "Student Seller",
  contact: "9809012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/thermos_flask.jpg"
},
{
  id: 37,
  name: "Bucket & Mug",
  category: "daily",
  price: 180,
  sellingPrice: 180,
  originalPrice: 350,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Bucket and mug set.",
  specs: { material: "Plastic" },
  sellerName: "Student Seller",
  contact: "9808012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/bucket.jpg"
},
{
  id: 38,
  name: "Cloth Hangers",
  category: "daily",
  price: 120,
  sellingPrice: 120,
  originalPrice: 250,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Plastic cloth hangers set.",
  specs: { quantity: "6" },
  sellerName: "Student Seller",
  contact: "9807012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/cloth_hanger.jpg"
},
{
  id: 39,
  name: "Iron Box",
  category: "daily",
  price: 900,
  sellingPrice: 900,
  originalPrice: 1800,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Electric iron box.",
  specs: { power: "1000W" },
  sellerName: "Student Seller",
  contact: "9806012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/iron_box.jpg"
},
{
  id: 40,
  name: "Study Lamp",
  category: "daily",
  price: 500,
  sellingPrice: 500,
  originalPrice: 1000,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Study lamp with focused light.",
  specs: { light: "LED" },
  sellerName: "Student Seller",
  contact: "9805012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/study_lamp.jpg"
},

/* ================= ACCESSORIES (10) ================= */
{
  id: 41,
  name: "Smart Watch",
  category: "accessories",
  price: 2500,
  sellingPrice: 2500,
  originalPrice: 4500,
  condition: "Like New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Smart watch with fitness tracking and notifications.",
  specs: { brand: "FitPro", battery: "7 days", waterproof: "Yes" },
  sellerName: "Student Seller",
  contact: "9794012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/power_bank.jpg"
},
{
  id: 42,
  name: "Backpack",
  category: "accessories",
  price: 800,
  sellingPrice: 800,
  originalPrice: 1500,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Durable backpack for daily college use.",
  specs: { capacity: "25L", compartments: "3", waterproof: "Yes" },
  sellerName: "Student Seller",
  contact: "9783012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/lunch_box.jpg"
},
{
  id: 43,
  name: "Sunglasses",
  category: "accessories",
  price: 600,
  sellingPrice: 600,
  originalPrice: 1200,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Stylish sunglasses with UV protection.",
  specs: { uv_protection: "400", material: "Plastic" },
  sellerName: "Student Seller",
  contact: "9772012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/headphones.jpg"
},
{
  id: 44,
  name: "Leather Wallet",
  category: "accessories",
  price: 350,
  sellingPrice: 350,
  originalPrice: 700,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Leather wallet with multiple card slots.",
  specs: { material: "Leather", card_slots: "8" },
  sellerName: "Student Seller",
  contact: "9761012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/mug.jpg"
},
{
  id: 45,
  name: "Formal Belt",
  category: "accessories",
  price: 250,
  sellingPrice: 250,
  originalPrice: 500,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Genuine leather belt for formal wear.",
  specs: { material: "Leather", size: "32 inches" },
  sellerName: "Student Seller",
  contact: "9750012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/cloth_hanger.jpg"
},
{
  id: 46,
  name: "Handbag",
  category: "accessories",
  price: 1200,
  sellingPrice: 1200,
  originalPrice: 2500,
  condition: "Like New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Elegant handbag for daily use.",
  specs: { material: "Synthetic", compartments: "2" },
  sellerName: "Student Seller",
  contact: "9739012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/lunch_box.jpg"
},
{
  id: 47,
  name: "Sports Shoes",
  category: "accessories",
  price: 1500,
  sellingPrice: 1500,
  originalPrice: 3000,
  condition: "Used",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Comfortable sports shoes for running and gym.",
  specs: { brand: "Nike", size: "UK 9" },
  sellerName: "Student Seller",
  contact: "9728012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/kettle.jpg"
},
{
  id: 48,
  name: "Sports Wristband",
  category: "accessories",
  price: 150,
  sellingPrice: 150,
  originalPrice: 300,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Silicone wristband for sports.",
  specs: { material: "Silicone", waterproof: "Yes" },
  sellerName: "Student Seller",
  contact: "9717012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/cloth_hanger.jpg"
},
{
  id: 49,
  name: "Keychain",
  category: "accessories",
  price: 100,
  sellingPrice: 100,
  originalPrice: 200,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Metal keychain with bottle opener.",
  specs: { material: "Metal", features: "Bottle opener" },
  sellerName: "Student Seller",
  contact: "9706012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/key_board.jpg"
},
{
  id: 50,
  name: "Formal Tie",
  category: "accessories",
  price: 300,
  sellingPrice: 300,
  originalPrice: 600,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Formal tie for interviews and events.",
  specs: { material: "Silk", color: "Navy Blue" },
  sellerName: "Student Seller",
  contact: "9695012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/cloth_hanger.jpg"
},

/* ================= OTHERS (10) ================= */
{
  id: 51,
  name: "Gaming Mouse Pad",
  category: "others",
  price: 400,
  sellingPrice: 400,
  originalPrice: 800,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Large gaming mouse pad with RGB lighting.",
  specs: { size: "Large", rgb: "Yes" },
  sellerName: "Student Seller",
  contact: "9684012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/mouse.jpg"
},
{
  id: 52,
  name: "Phone Stand",
  category: "others",
  price: 200,
  sellingPrice: 200,
  originalPrice: 400,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Adjustable phone stand for desk use.",
  specs: { material: "Plastic", adjustable: "Yes" },
  sellerName: "Student Seller",
  contact: "9673012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/laptop_stand.jpg"
},
{
  id: 53,
  name: "Cable Organizer",
  category: "others",
  price: 150,
  sellingPrice: 150,
  originalPrice: 300,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Cable organizer for desk management.",
  specs: { material: "Silicone", slots: "5" },
  sellerName: "Student Seller",
  contact: "9662012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/extension_box.jpg"
},
{
  id: 54,
  name: "Plant Pot",
  category: "others",
  price: 300,
  sellingPrice: 300,
  originalPrice: 600,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Ceramic plant pot for indoor plants.",
  specs: { material: "Ceramic", size: "Medium" },
  sellerName: "Student Seller",
  contact: "9651012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/bowl.jpg"
},
{
  id: 55,
  name: "Desk Organizer",
  category: "others",
  price: 500,
  sellingPrice: 500,
  originalPrice: 1000,
  condition: "Used",
  yearsUsed: 2,
  yearBought: 2023,
  description: "Multi-compartment desk organizer.",
  specs: { material: "Wood", compartments: "6" },
  sellerName: "Student Seller",
  contact: "9640012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},
{
  id: 56,
  name: "Digital Wall Clock",
  category: "others",
  price: 600,
  sellingPrice: 600,
  originalPrice: 1200,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Digital wall clock with temperature display.",
  specs: { type: "Digital", features: "Temperature, Date" },
  sellerName: "Student Seller",
  contact: "9629012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/study_lamp.jpg"
},
{
  id: 57,
  name: "Photo Frame",
  category: "others",
  price: 250,
  sellingPrice: 250,
  originalPrice: 500,
  condition: "New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "Wooden photo frame for memories.",
  specs: { material: "Wood", size: "8x10 inches" },
  sellerName: "Student Seller",
  contact: "9618012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/drawer_table.jpg"
},
{
  id: 58,
  name: "USB Mini Fan",
  category: "others",
  price: 350,
  sellingPrice: 350,
  originalPrice: 700,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "USB powered mini fan for desk.",
  specs: { power: "USB", speed: "3 speeds" },
  sellerName: "Student Seller",
  contact: "9607012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/power_bank.jpg"
},
{
  id: 59,
  name: "RGB LED Strip Lights",
  category: "others",
  price: 450,
  sellingPrice: 450,
  originalPrice: 900,
  condition: "Like New",
  yearsUsed: 0,
  yearBought: 2025,
  description: "RGB LED strip lights for room decoration.",
  specs: { length: "5m", colors: "RGB", remote: "Yes" },
  sellerName: "Student Seller",
  contact: "9596012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/study_lamp.jpg"
},
{
  id: 60,
  name: "Decorative Table Lamp",
  category: "others",
  price: 800,
  sellingPrice: 800,
  originalPrice: 1600,
  condition: "Good",
  yearsUsed: 1,
  yearBought: 2024,
  description: "Decorative table lamp with warm light.",
  specs: { material: "Glass", bulb_type: "LED" },
  sellerName: "Student Seller",
  contact: "9585012345",
  location: "Vignan University",
  dateAdded: "2025-02-01",
  available: true,
  image: "images/study_lamp.jpg"
}

];
